### ISSUE TITLE
Autoclose via scroll in Safari

### ISSUE THREAD

**Issue by jimmyjammyj** [dimsemenov/PhotoSwipe#1002] opened 2015-10-26 23:45 UTC
Hi there! Closing PhotoSwipe via scrolling in Safari 9.0 on OS X does not work. (Have not tried it on earlier versions though)

Jimmy

**Comment by dimsemenov** [comment] 2015-10-27 05:10
Duplicate of https://github.com/dimsemenov/PhotoSwipe/issues/983

**Closed by dimsemenov** 2015-10-27 05:10 UTC
