### ISSUE TITLE
Covering whole screen with a slide

### ISSUE THREAD

**Issue by marekstodolny** [dimsemenov/PhotoSwipe#921] opened 2015-07-30 07:44 UTC
Is there a way to make slides fit 100% to window height?
Like a div with overflow:hidden that contains a centered img with full height.

**Comment by dimsemenov** [comment] 2015-08-04 16:45
Duplicate of https://github.com/dimsemenov/PhotoSwipe/issues/795

**Closed by dimsemenov** 2015-08-04 16:45 UTC
