### ISSUE TITLE
Can't get Share to share image

### ISSUE THREAD

**Issue by jamminjames** [dimsemenov/PhotoSwipe#936] opened 2015-08-08 00:19 UTC
I've looked through the issues, but can't figure out what I'm doing wrong. When I use the share button, I can't seem to share the current image with Facebook or Twitter. The only one that will is Pinterest.

What do I need to do?

I have history set to true, and in the shareButtons section in photoswipe-ui-default.js, I have:

`		shareButtons: [
				{id:'facebook', label:'Share on Facebook', url:'https://www.facebook.com/sharer/sharer.php?u={{url}}&media={{image_url}}'},
				{id:'twitter', label:'Tweet', url:'https://twitter.com/intent/tweet?text={{text}}&url={{url}}&media={{image_url}}'},
				{id:'pinterest', label:'Pin it', url:'http://www.pinterest.com/pin/create/button/'+
													'?url={{url}}&media={{image_url}}&description={{text}}'},
				{id:'download', label:'Download image', url:'{{raw_image_url}}', download:true}
			],
			getImageURLForShare: function( shareButtonData ) {
				return pswp.currItem.src || '';
			},
			getPageURLForShare: function( shareButtonData ) {
				return window.location.href;
			},
			getTextForShare: function( shareButtonData ) {
				return pswp.currItem.title || '';
			}, `

**Comment by mjau-mjau** [comment] 2015-08-08 06:26
You are editing photoswipe-ui-default.js directly? shareButtons is an option in the PS options object. Also, what does it mean 'can't seem to share'? It shares, but the image doesn't show or what? I assume this must be online if you are testing ... Perhaps you have a link?

**Comment by dimsemenov** [comment] 2015-08-08 07:50
Duplicate of https://github.com/dimsemenov/PhotoSwipe/issues/749

**Closed by dimsemenov** 2015-08-08 07:50 UTC
