### ISSUE TITLE
RTL animation

### ISSUE THREAD

**Issue by 3zzy** [dimsemenov/PhotoSwipe#896] opened 2015-07-09 13:23 UTC
I'm able to get RTL (for my purpose) working with a simple change:

    if ( _options.rtl ) {
        if(totalShiftDist > MIN_SWIPE_DISTANCE && 
        	(isFastLastFlick || _releaseAnimData.lastFlickOffset.x > -20) ) {
        	// go to prev item
        	itemsDiff = 1;
        } else if(totalShiftDist < -MIN_SWIPE_DISTANCE && 
        	(isFastLastFlick || _releaseAnimData.lastFlickOffset.x < 20) ) {
        	// go to next item
        	itemsDiff = -1;
        }
    }

.. however, the animation is wrong, as you can see here: https://youtu.be/PZpFgC42TCM

Any pointers to fix that would be great.

Thanks!

**Comment by dimsemenov** [comment] 2015-07-11 08:32
It's not that simple as just changing this function. See https://github.com/dimsemenov/PhotoSwipe/issues/818#issuecomment-94653345

Closed, as duplicate of: https://github.com/dimsemenov/PhotoSwipe/issues/818

**Closed by dimsemenov** 2015-07-11 08:32 UTC

**Comment by 3zzy** [comment] 2015-07-11 09:34
Ok, and RTL isn't coming officially anytime soon?

**Comment by 3zzy** [comment] 2016-01-30 13:02
Is RTL supported now? :)
