### ISSUE TITLE
Uncaught TypeError: Cannot read property 'firstChild' of undefined

### ISSUE THREAD

**Issue by exileAU** [dimsemenov/PhotoSwipe#1223] opened 2016-10-08 07:31 UTC
Following your documentation I have come into this error while working at step 3. Any help would be appreciated.

Pastebin: http://pastebin.com/Yu6RV6pD

**Comment by dimsemenov** [comment] 2016-10-08 07:48
Your code is correct, make sure that you add JS after .pswp element or in document.ready.

Closed, duplicate of https://github.com/dimsemenov/PhotoSwipe/issues/833

**Closed by dimsemenov** 2016-10-08 07:48 UTC

**Comment by exileAU** [comment] 2016-10-08 08:48
Hey Mate, thanks for the reply. I also just ran into another error. 
Uncaught ReferenceError: PhotoSwipe is not defined
Any help is appreciated.
