### ISSUE TITLE
Slide won't loop on mobile when there is only two images.

### ISSUE THREAD

**Issue by nicholaelaw** [dimsemenov/PhotoSwipe#951] opened 2015-08-31 12:18 UTC
I think I've discovered a small inconsistency in pswp's behaviour on mobile browsers.

I stole the example code from the Creating an Array of Slide Objects chapter of [Getting Started](http://photoswipe.com/documentation/getting-started.html) wholesale, made absolutely no change to the code.

When you have 3 or more images in a slide, it loops (going next on the last image returns to the first) fine on both desktop and mobile browsers. But when there is only 2 images, desktop loops fine, on mobile (I'm on android, and I tested in Chrome's dev console) you can't swipe to the right to go back to the beginning.

You can replicate this in the [example](http://codepen.io/dimsemenov/pen/ZYbPJM), just delete the third image from the second gallery and try to swipe (on a mobile browser, of course).

**Comment by dimsemenov** [comment] 2015-08-31 14:59
Duplicate of https://github.com/dimsemenov/PhotoSwipe/issues/821

**Closed by dimsemenov** 2015-08-31 14:59 UTC
