### ISSUE TITLE
how to prevent the click the black backgroud  close the instance

### ISSUE THREAD

**Issue by jiuyuehe** [dimsemenov/PhotoSwipe#979] opened 2015-09-24 10:31 UTC
now, I'm click the black backgroud ,photoswipe  be closed ,who to prevent ?

**Comment by dimsemenov** [comment] 2015-10-03 16:26
Duplicate of https://github.com/dimsemenov/PhotoSwipe/issues/762.

**Closed by dimsemenov** 2015-10-03 16:26 UTC
