### ISSUE TITLE
Facebook displaying incorrect image thumbnails.

### ISSUE THREAD

**Issue by forchun** [dimsemenov/PhotoSwipe#1064] opened 2016-02-01 20:06 UTC
I have a client who has a gallery for his homepage which is ran by PhotoSwipe. When trying to share an image in his gallery onto Facebook, it displays the wrong image. 

I have tried everything here: https://github.com/dimsemenov/PhotoSwipe/issues/749

None of this seemed to have worked. 

```
                shareButtons: [{
                    id: "facebook",
                    label: "Share on Facebook",
                    url: "https://www.facebook.com/sharer/sharer.php?u={{url}}"
                }, {
                    id: "twitter",
                    label: "Tweet",
                    url: "https://twitter.com/intent/tweet?text={{text}}&url={{url}}"
                }, {
                    id: "pinterest",
                    label: "Pin it",
                    url: "http://www.pinterest.com/pin/create/button/?url={{url}}&media={{image_url}}&description={{text}}"
                }],
				
getImageURLForShare: function( shareButtonData ) {
    // `pswp` is the PhotoSwipe instance object,
    // you should define it by yourself
    return pswp.currItem.src;
},
getPageURLForShare: function( shareButtonData ) {
    return pswp.currItem.src;
}
```

When I change `"https://www.facebook.com/sharer/sharer.php?u={{url}}"` to `{{image_url}}` it shows the thumbnail that I want however it is just the image url and not the actual url of the slideshow when you click on the facebook post.

I have also tried adding` return pswp.currItem.attachmentURL;` instead of` pswp.curritem.src;` but that has not worked either. I'm losing my mind just trying to get the Facebook thumbnails to display properly!

Any help is very much appreciated!

**Comment by dimsemenov** [comment] 2016-02-01 21:16
Replied to your question here - https://github.com/dimsemenov/PhotoSwipe/issues/749#issuecomment-178196231

I'm closing this issue, as duplicate of #749.

**Closed by dimsemenov** 2016-02-01 21:16 UTC
