### ISSUE TITLE
cropped attribute not working

### ISSUE THREAD

**Issue by tiomanisland** [dimsemenov/PhotoSwipe#1858] opened 2022-03-04 17:56 UTC
I don't understand what is cropped parameter for?

    data-cropped="true" 

The website says just this:

Optional data-cropped="true" attribute if thumbnail is cropped.

What does that mean? If I want it to be cropped or if it was cropped before? Crop how? If I use true or false for this attribute nothing changes. Image still looks the same. I can't find any explanation about cropped behaviour.

**Comment by BilouMaster** [comment] 2022-03-04 18:05
This option impact the zooming transition when you open the lightbox, from cropped to full when your thumbnail doesn't show the full picture.

If your thumbnail shows the full picture you will see no difference.

It works for thumbnails "cropped" with CSS, like image contained into a div smaller than the image, the real thumbnail ressource still need to keep the same ratio to make it work.

**Comment by tiomanisland** [comment] 2022-03-04 19:01
Thanks. So if I have two images ready (big, thumbnail) exactly as they are supposed to be displayed, if won't affect anything?

Another question: where do I find more options for this line:

<div class="pswp-gallery pswp-gallery--single-column" id="gallery--simple">

**Comment by tiomanisland** [comment] 2022-03-04 19:26
I found a bug. If I add BAK__ to disable this line, everything still works

`<BAK___div class="pswp-gallery pswp-gallery--single-column" id="gallery--simple">`

But if I completely remove that line (which has BAK___div) in it, gallery stops working. Looks like things rely on this class although this is invalid tag (BAK__div). Why is that?

**Comment by dimsemenov** [comment] 2022-03-14 08:17
Closing, since there is no reduced test case, feel free to re-open if the issue is not resolved.

And refer to the cropped example on the Getting Started documentation page.

**Closed by dimsemenov** 2022-03-14 08:17 UTC
