### ISSUE TITLE
Info Panel

### ISSUE THREAD

**Issue by eman10** [dimsemenov/PhotoSwipe#859] opened 2015-06-09 17:44 UTC
Is there a way to implement a google photos style info panel? See white panel in attached image for an example.

![06 09 2015-13 35](https://cloud.githubusercontent.com/assets/903083/8065150/922e14a6-0ead-11e5-8e02-89805232d4d8.png)

**Comment by dimsemenov** [comment] 2015-06-09 18:15
Duplicate of #856.

**Closed by dimsemenov** 2015-06-09 18:15 UTC
