### ISSUE TITLE
How to get auto dimensions

### ISSUE THREAD

**Issue by ozknozsrt** [dimsemenov/PhotoSwipe#1068] opened 2016-02-11 10:06 UTC
Hi friends,

How is all photo get item attribute "data-size" auto dimension?

Thanks a lot

**Comment by dimsemenov** [comment] 2016-02-16 08:53
Closed as duplicate of https://github.com/dimsemenov/PhotoSwipe/issues/741

**Closed by dimsemenov** 2016-02-16 08:53 UTC
