### ISSUE TITLE
Make `w` and `h` optional and use `image.naturalWidth` and `image.naturalHeight`

### ISSUE THREAD

**Issue by moldcraft** [dimsemenov/PhotoSwipe#957] opened 2015-09-05 19:16 UTC
http://www.w3schools.com/jsref/prop_img_naturalwidth.asp

**Comment by dimsemenov** [comment] 2015-09-05 19:28
These properties can be read only after image is loaded, PhotoSwipe needs dimensions right away.

Duplicate of https://github.com/dimsemenov/PhotoSwipe/issues/741

**Closed by dimsemenov** 2015-09-05 19:28 UTC

**Comment by pedrovagner** [comment] 2016-12-12 00:20
Duplicated https://github.com/dimsemenov/PhotoSwipe/issues/664
