### ISSUE TITLE
Images not displaying at first

### ISSUE THREAD

**Issue by tbhockey** [dimsemenov/PhotoSwipe#1038] opened 2015-12-03 15:39 UTC
I'm experiencing a problem in Firefox (42 anyway) where the first image in the container is displayed, but as you cycle through the following images they are not displayed the first time around. Once they are hit for the second time (after cycling through it one time) those images will then display properly. For an example see here: https://systems-staging.audiogon.com/systems/5172

I was also getting the "will-change memory usage" alert discussed here https://github.com/dimsemenov/PhotoSwipe/issues/855 so I thought that might be related in some way. I implemented your suggested fix which caused the warning to go away, but had no affect on this issue.

At a loss at this point. Any thoughts appreciated.

**Comment by dimsemenov** [comment] 2015-12-03 15:57
Duplicate of #1014

**Closed by dimsemenov** 2015-12-03 15:57 UTC

**Comment by tbhockey** [comment] 2015-12-03 15:58
Figured there was one... thanks.
