### ISSUE TITLE
Problem with animation on cropped thumbnails

### ISSUE THREAD

**Issue by fotorunedotcom** [dimsemenov/PhotoSwipe#1009] opened 2015-11-07 11:08 UTC
On my website:
http://fotorune.com/
When you click on a thumbnail – that’s not square – as one of the nature photos - you can see the animation is resizing the image. It stretches the images for about a half second before it’s fitted.

This problem is only when there is different format between the thumbnail and the full res version of the images.

How can I make this animation/transition to be smooth? Is it possible to deactivate the “enlarging-animation-effect”? Other ideas?

**Comment by dimsemenov** [comment] 2015-11-07 17:01
http://photoswipe.com/documentation/faq.html#different-thumbnail-dimensions

Closed, as duplicate of https://github.com/dimsemenov/PhotoSwipe/issues/911

**Closed by dimsemenov** 2015-11-07 17:01 UTC
