### ISSUE TITLE
Square Thumbnails, none square large images

### ISSUE THREAD

**Issue by tobias-r** [dimsemenov/PhotoSwipe#964] opened 2015-09-09 08:17 UTC
Hi there,

I realised, that there is no support for a format change from thumbnail to large version.

The UI is jumping in this case.

Wouldn't it be easy to simply smoothly adjust the ratio? Facebook does it too in its app.

Or am I wrong and there is simply an option to activate to make this work?

Thanks
Tobi

**Comment by dimsemenov** [comment] 2015-09-09 09:00
Duplicate of #911

**Closed by dimsemenov** 2015-09-09 09:00 UTC
