### ISSUE TITLE
loadAndOpen method throws TypeError

### ISSUE THREAD

**Issue by band79** [dimsemenov/PhotoSwipe#1961] opened 2022-09-09 09:19 UTC
I want to remote open PhotoSwipe images, so I tried to use:
lightbox.loadAndOpen(0);

But this throws the following TypeError:

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'content')
    at PhotoSwipe.updatePreloaderVisibility (photoswipe.esm.js:3678:27)
    at photoswipe.esm.js:4307:18
    at Array.forEach (<anonymous>)
    at PhotoSwipe.dispatch (photoswipe.esm.js:4306:29)
    at PhotoSwipe.init (photoswipe.esm.js:5979:10)
    at PhotoSwipeLightbox._openPhotoswipe (photoswipe-lightbox.esm.js:1796:10)
    at photoswipe-lightbox.esm.js:1730:14

**Comment by dimsemenov** [comment] 2022-09-09 10:05
Duplicate of https://github.com/dimsemenov/PhotoSwipe/issues/1927#issuecomment-1145285913

**Closed by dimsemenov** 2022-09-09 10:05 UTC
